# pxpipe: loopback proxy that images the bulky parts of each Anthropic
# request before it leaves the machine (cells/repo/packages.nix). One system
# instance, not a user unit: the port is shared, two logged-in users (Entra
# on seat0, the local user over ssh) would fight over it. Stateless -- the
# API key travels in each request -- so sharing the instance leaks nothing.
#
# Hermes itself is installed here too, system-wide: the Entra user is an
# NSS-only account (no users.users, no home-manager), so systemPackages is
# the only PATH both sessions share. State stays per-user in ~/.hermes
# (persisted for both: layer-users-local.nix, auth-entra.nix), except
# skills/ and memories/, which are symlinks into /srv/agents/hermes
# (srv-agents.nix) so both accounts run against one skill tree and one
# MEMORY.md. Sessions stay per-user.
#
# Token diet for the agent's terminal:
#   nixq  shim named `nix` that collapses build/copy progress to one line. Not
#         in systemPackages: the agent packages carry it on their own PATH
#         (withNixq, cells/repo/packages.nix), so only agent shells get it.
#   rtk   pre_tool_call plugin rewrites `git status` -> `rtk git status` etc.
#         `rtk rewrite "nix ..."` is a passthrough (rc 1), so nix stays with
#         nixq; rtk never touches it.
{
  inputs,
  cell,
}: {
  config,
  lib,
  pkgs,
  ...
}: let
  inherit (inputs.cells.repo.packages) pxpipe hermes-agent rtk;
  port = 47821;
  proxyHost = "pxpipe.anthropic.com";
  # Hermes (hermes_cli/runtime_provider.py) takes the endpoint for
  # `provider: anthropic` from model.base_url in config.yaml only -- not from
  # ANTHROPIC_BASE_URL -- and only when the hostname ends in .anthropic.com.
  # HERMES_CONFIG is not read either, so the config has to be written into
  # each user's ~/.hermes.
  model = {
    provider = "anthropic";
    base_url = "http://${proxyHost}:${toString port}/anthropic";
    default = "claude-opus-5-5";
  };
  pinned =
    lib.mapAttrs' (k: lib.nameValuePair "model.${k}") model
    // {"display.skin" = "kanagawa";};
  # Missing keys inherit hermes' gold default skin (skin_engine.py:831), so
  # every key it reads is set. Unreachable: diff line bgs are derived from
  # ui_error/ui_ok (agent/display.py:74-82), not winterRed/winterGreen.
  # JSON is YAML; the loader only needs `name`.
  hermesSkin = let
    r = inputs.cells.common.theme.roles;
    c = inputs.cells.common.theme.colors;
    hex = lib.mapAttrs (_: v: "#${v}");
    skin = pkgs.writeText "skin.json" (builtins.toJSON {
      name = "kanagawa";
      description = "Kanagawa Wave, from cells/common/theme.nix";
      colors = hex {
        background = r.bg;
        banner_border = r.focus;
        banner_title = r.highlight;
        banner_accent = r.accent;
        banner_dim = r.muted;
        banner_text = r.fg;
        ui_accent = r.focus;
        ui_label = r.info;
        ui_ok = r.success;
        ui_error = r.urgent;
        ui_warn = r.warning;
        ui_tool = r.hover;
        ui_thinking = r.muted;
        prompt = r.fg;
        input_rule = c.sumiInk6;
        response_border = r.focus;
        shell_dollar = r.info;
        diff_added = r.diffAdd;
        diff_removed = r.diffDelete;
        diff_added_word = r.success;
        diff_removed_word = r.urgent;
        syntax_string = r.accent;
        syntax_number = c.surimiOrange;
        syntax_keyword = r.hover;
        syntax_comment = r.muted;
        status_bar_bg = r.bgAlt;
        status_bar_text = r.fg;
        status_bar_strong = r.highlight;
        status_bar_dim = r.muted;
        status_bar_good = r.success;
        status_bar_warn = r.highlight;
        status_bar_bad = r.warning;
        status_bar_critical = r.urgent;
        session_label = r.info;
        session_border = r.muted;
        voice_status_bg = r.bgAlt;
        selection_bg = r.selection;
        completion_menu_bg = r.bgAlt;
        completion_menu_current_bg = r.selection;
        completion_menu_meta_bg = r.bgAlt;
        completion_menu_meta_current_bg = r.selection;
      };
    });
    # The banner art's gold ladder, light to dark, onto a blue-violet one.
    artColors = pkgs.writeText "art-colors.json" (builtins.toJSON (hex {
      FFD700 = c.lightBlue;
      FFBF00 = c.springBlue;
      CD7F32 = c.crystalBlue;
      B8860B = c.springViolet1;
    }));
  in
    # The logo and caduceus are Rich markup with literal golds (banner.py:70,
    # 77); a skin replaces them only whole. Taken from the pinned hermes so
    # a bump that changes the art or its colours fails here, not silently.
    pkgs.runCommand "hermes-skin-kanagawa.yaml" {} ''
      ${lib.getExe pkgs.python3} ${./__hermes-skin-art.py} \
        ${hermes-agent}/lib/python3*/site-packages/hermes_cli/banner.py \
        ${skin} ${artColors} $out
    '';
  # The plugin rtk ships, generated by the pinned rtk itself so the adapter
  # and the `rtk rewrite` exit-code contract cannot drift. Pure: `rtk init`
  # only writes under $HOME.
  rtkPlugin =
    pkgs.runCommand "rtk-hermes-plugin" {
      env.RTK_TELEMETRY_DISABLED = "1";
    } ''
      export HOME="$TMPDIR/home"
      mkdir -p "$HOME"
      ${lib.getExe rtk} init -g --agent hermes >/dev/null
      cp -r "$HOME/.hermes/plugins/rtk-rewrite" "$out"
    '';
  # Hermes owns config.yaml (it rewrites _config_version and onboarding
  # flags), so a store symlink is out; `hermes config set` merges a key into
  # the existing file instead. Only `pinned` is -- the API key stays the
  # user's (~/.hermes/auth.json); a `/skin` choice resets on the next login.
  # plugins.enabled is a list:
  # rtk-rewrite is appended, whatever the user enabled themselves stays.
  # Plugin discovery scans ~/.hermes/plugins/<dir> with is_dir(), which
  # follows the store symlink.
  #
  # The Entra user's $HOME is created by himmelblau while the session is
  # opening (see home-manager-entra in layer-compositor.nix), so on the
  # first login after a boot it may not exist yet: wait, don't fail.
  seedHermes = pkgs.writeShellScript "hermes-seed-proxy" ''
    set -eu
    for _ in $(seq 1 120); do
      [ -d "$HOME" ] && break
      sleep 0.5
    done
    [ -d "$HOME" ] || { echo "no $HOME after 60s" >&2; exit 1; }
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: ''
        if [ "$(${lib.getExe hermes-agent} config get ${k} 2>/dev/null || true)" != ${lib.escapeShellArg v} ]; then
          ${lib.getExe hermes-agent} config set ${k} ${lib.escapeShellArg v}
        fi
      '')
      pinned)}

    mkdir -p "$HOME/.hermes/skins"
    ln -sfn ${hermesSkin} "$HOME/.hermes/skins/kanagawa.yaml"

    # skills/ and memories/ are shared by both accounts: /srv/agents/hermes
    # (srv-agents.nix). A real directory here is pre-migration per-user state;
    # leave it alone and let a human merge it, do not silently swap it out.
    for d in skills memories; do
      if [ -d "$HOME/.hermes/$d" ] && [ ! -L "$HOME/.hermes/$d" ]; then
        echo "~/.hermes/$d is a real directory, not linking /srv/agents/hermes/$d over it" >&2
      else
        ln -sfn "/srv/agents/hermes/$d" "$HOME/.hermes/$d"
      fi
    done

    mkdir -p "$HOME/.hermes/plugins"
    # A real directory here is a hand-run `rtk init` of some other version;
    # ours is the pinned one.
    [ -d "$HOME/.hermes/plugins/rtk-rewrite" ] && [ ! -L "$HOME/.hermes/plugins/rtk-rewrite" ] && rm -rf "$HOME/.hermes/plugins/rtk-rewrite"
    ln -sfn ${rtkPlugin} "$HOME/.hermes/plugins/rtk-rewrite"
    enabled=$(${lib.getExe hermes-agent} config get plugins.enabled 2>/dev/null || true)
    if ! printf '%s\n' "$enabled" | grep -qx -- '- rtk-rewrite'; then
      rest=$(printf '%s\n' "$enabled" | sed -n 's/^- \(.*\)$/"\1",/p' | tr -d '\n')
      ${lib.getExe hermes-agent} config set plugins.enabled "[''${rest}\"rtk-rewrite\"]"
    fi
  '';
in {
  environment.systemPackages = [
    hermes-agent
    rtk
  ];

  environment.variables = {
    # nixq (in the agents' PATH) must exec exactly the client the system was
    # built with, not "first nix on PATH that isn't me".
    NIXQ_REAL_NIX = "${config.nix.package}/bin/nix";
    RTK_TELEMETRY_DISABLED = "1";
  };

  systemd.services.pxpipe = {
    description = "pxpipe: Anthropic loopback proxy";
    wantedBy = ["multi-user.target"];
    after = ["network-online.target"];
    wants = ["network-online.target"];
    serviceConfig = {
      ExecStart = "${lib.getExe pxpipe} -port ${toString port}";
      Restart = "on-failure";
      RestartSec = 2;
      DynamicUser = true;
      # Nothing on disk, nothing to reach but the loopback listener and
      # api.anthropic.com.
      PrivateTmp = true;
      ProtectSystem = "strict";
      ProtectHome = true;
      NoNewPrivileges = true;
      RestrictAddressFamilies = ["AF_INET" "AF_INET6"];
      CapabilityBoundingSet = "";
    };
  };

  networking.hosts."127.0.0.1" = [proxyHost];

  # Per-user: every login (local user over ssh/greetd, Entra user on seat0)
  # gets model.* pointed at the proxy. Idempotent, so a no-op on later logins.
  systemd.user.services.hermes-seed-proxy = {
    description = "Point ~/.hermes/config.yaml at the pxpipe proxy, enable the rtk plugin, link shared skills/memories";
    wantedBy = ["default.target"];
    path = [pkgs.coreutils pkgs.gnugrep pkgs.gnused];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = seedHermes;
      TimeoutStartSec = "180s";
    };
  };
}
