# Agent CLIs shared by both accounts: claude-code and opencode (+
# oh-my-openagent) as packages, per-home state under $HOME.
#
#   - opencode: omo.jsonc carries the opencode-go/* models flattened to top
#     level; anthropic is not used.
#   - claude reaches pxpipe (profiles/agent-proxy.nix) via ANTHROPIC_BASE_URL
#     in settings.json env.
#   - rtk: the claude PreToolUse hook and RTK.md that `rtk init -g` would
#     write, plus ~/.config/rtk/config.toml.
#
# Packages come from cells/repo (the llm-agents pin lives there), passed in
# as `agentPkgs` from ../default.nix because home/ has no `inputs`.
#
# Store-backed, except omo.jsonc: oh-my-openagent rewrites its config in place
# on load (self-migration between versions) and a read-only store file makes
# that fail, so that one file is live-edited from
# /srv/the-hive/dotfiles/opencode like nvim/tmux/zsh.
#
# Credentials are not declared: `opencode auth login` (OpenCode Go key) and
# `claude` login once per account; both persist under the account's
# ~/.local/share/opencode / ~/.claude (layer-users-local, auth-entra).
{
  config,
  pkgs,
  lib,
  agentPkgs,
  theme,
  ...
}: let
  skills = import ./agents/skills.nix {inherit lib;};
  inherit (agentPkgs) claude-code opencode oh-my-opencode rtk herdr-integrations;

  # Local-plugin shim (~/.config/opencode/plugins/*.ts is auto-discovered):
  # re-exports the Nix-built bundle so the loaded plugin and the
  # `oh-my-opencode` CLI are the same derivation. Two exports: `export *`
  # does not re-export `default`. The entrypoint path is checked at build
  # time; builtins.pathExists would force oh-my-opencode to be realised
  # during eval, building npm deps on every `nix eval` of the host.
  omoPluginEntry = "${oh-my-opencode}/lib/oh-my-opencode/dist/index.js";
  omoShim = pkgs.runCommand "oh-my-openagent.ts" {} ''
    test -f ${omoPluginEntry} || {
      echo "oh-my-opencode plugin entrypoint moved -- update the shim path in home/dev/agents.nix" >&2
      exit 1
    }
    printf '%s\n' \
      'export * from "${omoPluginEntry}";' \
      'export { default } from "${omoPluginEntry}";' > $out
  '';

  # What `rtk init -g` writes for the model to read, generated by the pinned
  # rtk so it cannot drift from the hook. The hook itself is declared in
  # settings.json below; the `@RTK.md` include is prepended to CLAUDE.md.
  rtkMd = pkgs.runCommand "rtk-claude-md" {env.RTK_TELEMETRY_DISABLED = "1";} ''
    export HOME="$TMPDIR/home" CLAUDE_CONFIG_DIR="$TMPDIR/home/.claude"
    mkdir -p "$CLAUDE_CONFIG_DIR"
    ${lib.getExe rtk} init -g >/dev/null 2>&1 || true
    cp "$CLAUDE_CONFIG_DIR/RTK.md" "$out"
  '';

  claudeSettings = {
    env = {
      # pxpipe, profiles/agent-proxy.nix (host + port live there). Set here
      # rather than system-wide so pxpipe itself, which reads the same
      # variable for ITS upstream, never sees it.
      ANTHROPIC_BASE_URL = "http://pxpipe.anthropic.com:47821/anthropic";
      CLAUDE_CODE_MAX_OUTPUT_TOKENS = "8000";
      DISABLE_NON_ESSENTIAL_MODEL_CALLS = "1";
      DISABLE_COST_WARNINGS = "1";
      DISABLE_TELEMETRY = "1";
    };
    hooks = {
      # herdr: reports the session id to the pane it runs in, for restore
      # after a server restart. Same entry `herdr integration install claude`
      # writes (packages.nix herdr-integrations asserts it), so `herdr
      # integration status` sees it as installed.
      SessionStart = [
        {
          matcher = "^(startup|resume|clear|compact|fork)$";
          hooks = [
            {
              type = "command";
              command = "bash '${config.home.homeDirectory}/.claude/hooks/herdr-agent-state.sh' session";
              timeout = 10;
            }
          ];
        }
      ];
      # rtk rewrites `git status` etc. to their compact forms before the
      # shell runs them (`rtk init -g` would add exactly this).
      PreToolUse = [
        {
          matcher = "Bash";
          hooks = [
            {
              type = "command";
              command = "${lib.getExe rtk} hook claude";
            }
          ];
        }
      ];
      # Auto-commit per edit.
      PostToolUse = [
        {
          matcher = "Edit";
          hooks = [
            {
              type = "command";
              command = ''if git rev-parse --git-dir >/dev/null 2>&1 && [[ -n "$CLAUDE_TOOL_FILE_PATH" ]]; then git add "$CLAUDE_TOOL_FILE_PATH" 2>/dev/null; CHANGED_LINES=$(git diff --cached --numstat "$CLAUDE_TOOL_FILE_PATH" 2>/dev/null | awk '{print $1+$2}'); if [[ $CHANGED_LINES -gt 0 ]]; then FILENAME=$(basename "$CLAUDE_TOOL_FILE_PATH"); if [[ $CHANGED_LINES -lt 10 ]]; then SIZE="minor"; elif [[ $CHANGED_LINES -lt 50 ]]; then SIZE="moderate"; else SIZE="major"; fi; MSG="Update $FILENAME: $SIZE changes ($CHANGED_LINES lines)"; git commit -m "$MSG" "$CLAUDE_TOOL_FILE_PATH" 2>/dev/null || true; fi; fi'';
            }
          ];
        }
        {
          matcher = "Write";
          hooks = [
            {
              type = "command";
              command = ''if git rev-parse --git-dir >/dev/null 2>&1 && [[ -n "$CLAUDE_TOOL_FILE_PATH" ]]; then git add "$CLAUDE_TOOL_FILE_PATH" 2>/dev/null; FILENAME=$(basename "$CLAUDE_TOOL_FILE_PATH"); git commit -m "Add new file: $FILENAME" "$CLAUDE_TOOL_FILE_PATH" 2>/dev/null || true; fi'';
            }
          ];
        }
      ];
    };
    statusLine = {
      type = "command";
      command = "~/.claude/statusline.sh";
    };
    enabledPlugins."claude-security@claude-plugins-official" = true;
    extraKnownMarketplaces.claude-plugins-official.source = {
      source = "github";
      repo = "anthropics/claude-plugins-official";
    };
    alwaysThinkingEnabled = true;
    # Beats the `theme` that /theme writes to ~/.claude.json.
    theme = "custom:kanagawa";
  };

  # ~/.claude/themes/<slug>.json. Claude drops an override SILENTLY when the
  # key is not in the `base` palette or the value does not parse, so the set
  # below is exactly the 72 keys of 2.1.239's dark palette.
  claudeTheme = let
    r = theme.roles;
    c = theme.colors;
  in {
    name = "Kanagawa";
    base = "dark";
    overrides = lib.mapAttrs (_: v: "#${v}") {
      text = r.fg;
      inverseText = r.bg;
      inactive = r.muted;
      inactiveShimmer = c.oldWhite;
      subtle = c.sumiInk6;
      promptBorder = c.sumiInk6;
      promptBorderShimmer = r.muted;
      suggestion = r.focus;
      remember = r.focus;
      permission = r.focus;
      permissionShimmer = r.info;
      claudeBlue_FOR_SYSTEM_SPINNER = r.focus;
      claudeBlueShimmer_FOR_SYSTEM_SPINNER = r.info;
      rate_limit_fill = r.focus;
      rate_limit_empty = r.border;
      ide = r.info;
      professionalBlue = r.focus;
      # A cyan accent (dialog titles), not the screen bg.
      background = c.waveAqua2;
      planMode = c.waveAqua1;
      autoAccept = r.hover;
      autoAcceptShimmer = c.oniViolet2;
      skill = r.hover;
      merged = r.hover;
      effortUltra = r.hover;
      bashBorder = c.sakuraPink;
      claude = c.surimiOrange;
      claudeShimmer = r.highlight;
      clawd_body = c.surimiOrange;
      clawd_background = r.bgDim;
      briefLabelYou = r.info;
      briefLabelClaude = c.surimiOrange;
      fastMode = r.warning;
      fastModeShimmer = r.highlight;
      chromeYellow = r.highlight;
      success = r.success;
      error = r.urgent;
      warning = r.warning;
      warningShimmer = r.highlight;
      # Line bgs (plain and dimmed variant).
      diffAdded = r.diffAdd;
      diffRemoved = r.diffDelete;
      diffAddedDimmed = r.diffAdd;
      diffRemovedDimmed = r.diffDelete;
      # Word bg in diffs AND the fg of the +N/-N counts: must read both ways.
      diffAddedWord = c.autumnGreen;
      diffRemovedWord = r.urgent;
      userMessageBackground = r.bgAlt;
      userMessageBackgroundHover = r.border;
      composerSidebarBackground = c.sumiInk1;
      bashMessageBackgroundColor = r.bgAlt;
      memoryBackgroundColor = c.waveBlue1;
      selectionBg = r.selection;
      red_FOR_SUBAGENTS_ONLY = c.waveRed;
      blue_FOR_SUBAGENTS_ONLY = c.crystalBlue;
      green_FOR_SUBAGENTS_ONLY = c.springGreen;
      yellow_FOR_SUBAGENTS_ONLY = c.carpYellow;
      purple_FOR_SUBAGENTS_ONLY = c.oniViolet;
      orange_FOR_SUBAGENTS_ONLY = c.surimiOrange;
      pink_FOR_SUBAGENTS_ONLY = c.sakuraPink;
      cyan_FOR_SUBAGENTS_ONLY = c.waveAqua2;
      rainbow_red = c.waveRed;
      rainbow_orange = c.surimiOrange;
      rainbow_yellow = c.carpYellow;
      rainbow_green = c.springGreen;
      rainbow_blue = c.springBlue;
      rainbow_indigo = c.crystalBlue;
      rainbow_violet = c.oniViolet;
      rainbow_red_shimmer = c.peachRed;
      rainbow_orange_shimmer = c.roninYellow;
      rainbow_yellow_shimmer = c.oldWhite;
      rainbow_green_shimmer = c.waveAqua2;
      rainbow_blue_shimmer = c.lightBlue;
      rainbow_indigo_shimmer = c.springBlue;
      rainbow_violet_shimmer = c.oniViolet2;
    };
  };

  opencodeConfig = {
    "$schema" = "https://opencode.ai/config.json";
    model = "opencode-go/glm-5.2";
    plugin = ["@franlol/opencode-md-table-formatter@0.0.3"];
    autoupdate = false;
  };

  # ~/.config/opencode/themes/kanagawa.json shadows the built-in `kanagawa`,
  # whose yellows and diff hexes are off-palette. The 48 keys of the
  # built-in; syntax/markdown follow kanagawa.nvim wave, as nvim and bat do.
  # diffHighlight* are the +/- sign fg, not word bgs.
  opencodeTheme = let
    r = theme.roles;
    c = theme.colors;
  in {
    "$schema" = "https://opencode.ai/theme.json";
    theme = lib.mapAttrs (_: v: "#${v}") {
      primary = r.focus;
      secondary = r.hover;
      accent = c.sakuraPink;
      error = r.urgent;
      warning = r.warning;
      success = r.success;
      info = r.info;
      text = r.fg;
      textMuted = r.muted;
      background = r.bg;
      backgroundPanel = r.bgAlt;
      backgroundElement = r.border;
      border = c.sumiInk6;
      borderActive = r.focus;
      borderSubtle = r.border;
      diffAdded = r.success;
      diffRemoved = r.urgent;
      diffContext = r.muted;
      diffHunkHeader = r.info;
      diffHighlightAdded = r.success;
      diffHighlightRemoved = r.urgent;
      diffAddedBg = r.diffAdd;
      diffRemovedBg = r.diffDelete;
      diffContextBg = r.bgAlt;
      diffLineNumber = r.muted;
      diffAddedLineNumberBg = r.diffAdd;
      diffRemovedLineNumberBg = r.diffDelete;
      markdownText = r.fg;
      markdownHeading = c.crystalBlue;
      markdownLink = c.springBlue;
      markdownLinkText = c.crystalBlue;
      markdownCode = c.springGreen;
      markdownBlockQuote = c.oniViolet2;
      markdownEmph = c.carpYellow;
      markdownStrong = c.roninYellow;
      markdownHorizontalRule = r.muted;
      markdownListItem = c.springViolet1;
      markdownListEnumeration = c.springViolet1;
      markdownImage = c.crystalBlue;
      markdownImageText = c.springBlue;
      markdownCodeBlock = r.fg;
      syntaxComment = c.fujiGray;
      syntaxKeyword = c.oniViolet;
      syntaxFunction = c.crystalBlue;
      syntaxVariable = c.fujiWhite;
      syntaxString = c.springGreen;
      syntaxNumber = c.sakuraPink;
      syntaxType = c.waveAqua2;
      syntaxOperator = c.boatYellow2;
      syntaxPunctuation = c.springViolet1;
    };
  };

  opencodeTui = {
    "$schema" = "https://opencode.ai/tui.json";
    theme = "kanagawa";
    plugin = [];
  };

  # fuzzel (layer-shell, over the foot window) picks agent kind then cwd;
  # first cwd row is the focused pane's dir so Enter-Enter clones "this
  # agent, here". Reads HERDR_ACTIVE_PANE_CWD when run from a herdr
  # keys.command, else asks the socket for the focused pane.
  herdrSpawnAgent = pkgs.writeShellScriptBin "herdr-spawn-agent" ''
    set -eu
    PATH=${lib.makeBinPath [pkgs.jq pkgs.fuzzel pkgs.coreutils pkgs.gawk pkgs.gnugrep]}:$PATH
    cur=''${HERDR_ACTIVE_PANE_CWD:-}
    [ -n "$cur" ] || cur=$(herdr pane list | jq -r '.result.panes[] | select(.focused) | .cwd')
    kind=$(printf 'hermes\nclaude\nopencode\n' | fuzzel --dmenu --prompt 'agent > ' --lines 3) || exit 0
    cwd=$({ echo "$cur"; herdr pane list | jq -r '.result.panes[].cwd'
            command -v zoxide >/dev/null && zoxide query -l; } | awk 'NF && !s[$0]++' \
          | fuzzel --dmenu --prompt "$kind in > " --lines 12) || exit 0
    [ -d "$cwd" ] || exit 1
    # Agent names are global; several agents per dir is the normal case
    # (hermes + claude on the same repo), so suffix on collision.
    base="$(basename "$cwd")-$kind"
    taken=$(herdr agent list | jq -r '.result.agents[].name // empty')
    name=$base; n=2
    while printf '%s\n' "$taken" | grep -qx "$name"; do name="$base-$n"; n=$((n + 1)); done
    pane=$(herdr workspace create --cwd "$cwd" --focus --label "$name" | jq -r .result.root_pane.pane_id)
    # agent_not_ready is claude's trust prompt in a new dir, not a failure:
    # the agent is running and the pane is focused, answer it there.
    # herdr prints errors on stderr, so capture both streams.
    out=$(herdr agent start "$name" --kind "$kind" --pane "$pane" 2>&1) && exit 0
    code=$(printf '%s' "$out" | jq -r '.error.code // empty' 2>/dev/null || true)
    [ "$code" = agent_not_ready ] && exit 0
    printf '%s\n' "$out" >&2
    herdr workspace close "$(printf '%s' "$pane" | cut -d: -f1)" >/dev/null 2>&1 || true
    exit 1
  '';

  # herdr UI on the repo palette. panel_bg/sidebar_bg unset = foot's bg.
  # onboarding = false: the welcome screen would install integrations by
  # hand, they are declared here instead. Store-backed, so the in-app
  # settings cannot save; edit here.
  herdrConfig = {
    onboarding = false;
    # Mirrors dotfiles/tmux/config.conf so the two tags feel the same:
    # C-Up/Down walks the agent list (tmux: panes), C-,/. walks workspaces
    # (tmux: windows), M-1..9 jumps (dwl holds Super, Alt is free),
    # C-S-Enter spawns an agent (tmux: split in cwd), C-S-w/q/f close/zoom.
    # foot already emits every C-S-* chord as CSI-u (home/default.nix).
    # C-n/C-p stay on prefix: unconditional here, and they are prompt
    # history inside hermes/claude. split_horizontal stays prefix+minus.
    keys = {
      prefix = "ctrl+shift+b";
      previous_agent = "ctrl+up";
      next_agent = "ctrl+down";
      focus_pane_left = "ctrl+left";
      focus_pane_right = "ctrl+right";
      previous_workspace = "ctrl+comma";
      next_workspace = "ctrl+period";
      switch_workspace = "alt+1..9";
      # No new_tab: one agent = one workspace, tabs inside it are unused.
      close_pane = "ctrl+shift+w";
      close_workspace = "ctrl+shift+q";
      zoom = "ctrl+shift+f";
      resize_pane_left = "ctrl+shift+left";
      resize_pane_right = "ctrl+shift+right";
      resize_pane_up = "ctrl+shift+up";
      resize_pane_down = "ctrl+shift+down";
      command = [
        {
          key = "ctrl+shift+enter";
          type = "shell";
          command = "${herdrSpawnAgent}/bin/herdr-spawn-agent";
          description = "spawn agent (fuzzel: kind, cwd)";
        }
      ];
    };
    theme = {
      name = "kanagawa";
      custom = lib.mapAttrs (_: v: "#${v}") (let
        r = theme.roles;
        c = theme.colors;
      in {
        accent = r.focus;
        active_row_bg = r.bgAlt;
        selection_bg = r.selection;
        surface_dim = c.sumiInk1;
        surface0 = r.bgAlt;
        surface1 = r.border;
        overlay0 = c.sumiInk6;
        overlay1 = r.muted;
        text = r.fg;
        subtext0 = c.oldWhite;
        mauve = r.hover;
        green = r.success;
        yellow = r.highlight;
        red = r.urgent;
        blue = r.focus;
        teal = c.waveAqua2;
        peach = c.surimiOrange;
      });
    };
  };
  # herdr writes these itself on a live install; force: that install (or
  # the welcome screen) may already have left real files here.
  herdrFile = source: {
    inherit source;
    force = true;
  };
  json = pkgs.formats.json {};
in {
  home.packages =
    [
      claude-code
      opencode
      oh-my-opencode
      pkgs.bun # opencode's plugin system
      pkgs.ast-grep # oh-my-opencode
      pkgs.jq # statusline.sh
      herdrSpawnAgent # also callable from a shell / future dwl bind
    ]
    ++ skills.packages pkgs;

  home.file =
    {
      ".claude/settings.json".source = json.generate "claude-settings.json" claudeSettings;
      ".claude/themes/kanagawa.json".source = json.generate "claude-theme-kanagawa.json" claudeTheme;
      ".claude/statusline.sh" = {
        source = ./agents/statusline.sh;
        executable = true;
      };
      ".claude/RTK.md".source = rtkMd;
      # Global instructions: the rtk include first, then agents/CLAUDE.md
      # (tracked here, empty today). Store-backed, so claude's `#` quick-add
      # to the user file fails -- edit agents/CLAUDE.md instead.
      ".claude/CLAUDE.md".text = "@RTK.md\n" + builtins.readFile ./agents/CLAUDE.md;
      ".claude/hooks/herdr-agent-state.sh" = herdrFile "${herdr-integrations}/claude/herdr-agent-state.sh";
      ".omo/omo.jsonc".source =
        config.lib.file.mkOutOfStoreSymlink "/srv/the-hive/dotfiles/opencode/omo.jsonc";
    }
    // skills.mkSkillFiles ".claude/skills";

  xdg.configFile =
    {
      "opencode/opencode.json".source = json.generate "opencode.json" opencodeConfig;
      "opencode/tui.json".source = json.generate "tui.json" opencodeTui;
      "opencode/themes/kanagawa.json".source = json.generate "opencode-theme-kanagawa.json" opencodeTheme;
      # `omo doctor` will still say "not registered" -- it only knows the npm
      # route; ignore that line.
      "opencode/plugins/oh-my-openagent.ts".source = omoShim;
      # herdr: server plugin (auto-discovered), V1 TUI plugin registered in
      # tui.jsonc (the file herdr's status checks; opencode reads it next to
      # tui.json), V2 TUI entry in cli.json.
      "opencode/plugins/herdr-agent-state.js" = herdrFile "${herdr-integrations}/opencode/plugins/herdr-agent-state.js";
      "opencode/herdr-tui-session.js" = herdrFile "${herdr-integrations}/opencode/herdr-tui-session.js";
      "opencode/herdr-opencode/tui.js" = herdrFile "${herdr-integrations}/opencode/herdr-opencode/tui.js";
      "opencode/tui.jsonc" = herdrFile (json.generate "opencode-tui.jsonc" {plugin = ["./herdr-tui-session.js"];});
      "opencode/cli.json" = herdrFile (json.generate "opencode-cli.json" {plugins = ["./herdr-opencode"];});

      "herdr/config.toml" = herdrFile ((pkgs.formats.toml {}).generate "herdr-config.toml" herdrConfig);

      # rtk config. Telemetry is already off via RTK_TELEMETRY_DISABLED
      # (agent-proxy.nix); nix stays with nixq.
      "rtk/config.toml".source = (pkgs.formats.toml {}).generate "rtk-config.toml" {
        hooks.exclude_commands = ["nix" "nixos-rebuild" "colmena" "nom" "just"];
        tee = {
          enabled = true;
          mode = "failures";
        };
        telemetry.enabled = false;
      };
    }
    // skills.mkSkillFiles "opencode/skills";
}
