# Agent CLIs shared by both accounts: claude-code and opencode (+
# oh-my-openagent) as packages, per-home state under $HOME. Ported from
# jarvis's users/shared/tui/coding-agents with the decisions from
# port-jarvis-home applied:
#   - oh-my-claudecode marketplace wiring dropped (hermes + opencode now);
#     the two jarvis-local directory marketplaces are gone with it.
#   - opencode: anthropic is no longer used. omo.jsonc keeps only what was the
#     `go` profile (opencode-go/* models), flattened to top level so it is
#     THE config; the opencode-anthropic-oauth plugin and the OMO_PROFILE
#     aliases go away.
#   - claude reaches pxpipe (profiles/agent-proxy.nix) via ANTHROPIC_BASE_URL
#     in settings.json env, as on jarvis.
#   - rtk (post-dellvis-tooling §3): the claude PreToolUse hook and RTK.md
#     that `rtk init -g` would write, plus ~/.config/rtk/config.toml.
#
# Packages come from cells/repo (the llm-agents pin lives there), passed in
# as `agentPkgs` from ../default.nix because home/ has no `inputs`.
#
# Store-backed on purpose, except omo.jsonc: oh-my-openagent rewrites its
# config in place on load (self-migration between versions) and a read-only
# store file made it fail on jarvis, so that one file is live-edited from
# /srv/the-hive/dotfiles/opencode like nvim/tmux/zsh.
#
# Credentials are NOT declared: `opencode auth login` (OpenCode Go key) and
# `claude` login once per account; both persist under the account's
# ~/.local/share/opencode / ~/.claude (layer-users-local, auth-entra).
{
  config,
  pkgs,
  lib,
  agentPkgs,
  ...
}: let
  skills = import ./agents/skills.nix {inherit lib;};
  inherit (agentPkgs) claude-code opencode oh-my-opencode rtk;

  # Local-plugin shim (~/.config/opencode/plugins/*.ts is auto-discovered):
  # re-exports the Nix-built bundle so the loaded plugin and the
  # `oh-my-opencode` CLI are the same derivation. Two exports: `export *`
  # does not re-export `default`. The entrypoint path is checked at BUILD
  # time (jarvis used builtins.pathExists, which forces oh-my-opencode to be
  # realised during eval -- every `nix eval` of the host built npm deps).
  omoPluginEntry = "${oh-my-opencode}/lib/oh-my-opencode/dist/index.js";
  omoShim = pkgs.runCommand "oh-my-openagent.ts" {} ''
    test -f ${omoPluginEntry} || {
      echo "oh-my-opencode plugin entrypoint moved -- update the shim path in home/dev/agents.nix" >&2
      exit 1
    }
    printf '%s\n' \
      'export * from "${omoPluginEntry}";' \
      'export { default } from "${omoPluginEntry}";' > $out
  '';

  # What `rtk init -g` writes for the model to read, generated by the pinned
  # rtk so it cannot drift from the hook. The hook itself is declared in
  # settings.json below; CLAUDE.md stays the user's (add `@RTK.md` there).
  rtkMd = pkgs.runCommand "rtk-claude-md" {env.RTK_TELEMETRY_DISABLED = "1";} ''
    export HOME="$TMPDIR/home" CLAUDE_CONFIG_DIR="$TMPDIR/home/.claude"
    mkdir -p "$CLAUDE_CONFIG_DIR"
    ${lib.getExe rtk} init -g >/dev/null 2>&1 || true
    cp "$CLAUDE_CONFIG_DIR/RTK.md" "$out"
  '';

  claudeSettings = {
    env = {
      # pxpipe, profiles/agent-proxy.nix (host + port live there). Set here
      # rather than system-wide so pxpipe itself, which reads the same
      # variable for ITS upstream, never sees it.
      ANTHROPIC_BASE_URL = "http://pxpipe.anthropic.com:47821/anthropic";
      CLAUDE_CODE_MAX_OUTPUT_TOKENS = "8000";
      DISABLE_NON_ESSENTIAL_MODEL_CALLS = "1";
      DISABLE_COST_WARNINGS = "1";
      DISABLE_TELEMETRY = "1";
    };
    hooks = {
      # rtk rewrites `git status` etc. to their compact forms before the
      # shell runs them (`rtk init -g` would add exactly this).
      PreToolUse = [
        {
          matcher = "Bash";
          hooks = [
            {
              type = "command";
              command = "${lib.getExe rtk} hook claude";
            }
          ];
        }
      ];
      # jarvis's auto-commit-per-edit hooks, verbatim.
      PostToolUse = [
        {
          matcher = "Edit";
          hooks = [
            {
              type = "command";
              command = ''if git rev-parse --git-dir >/dev/null 2>&1 && [[ -n "$CLAUDE_TOOL_FILE_PATH" ]]; then git add "$CLAUDE_TOOL_FILE_PATH" 2>/dev/null; CHANGED_LINES=$(git diff --cached --numstat "$CLAUDE_TOOL_FILE_PATH" 2>/dev/null | awk '{print $1+$2}'); if [[ $CHANGED_LINES -gt 0 ]]; then FILENAME=$(basename "$CLAUDE_TOOL_FILE_PATH"); if [[ $CHANGED_LINES -lt 10 ]]; then SIZE="minor"; elif [[ $CHANGED_LINES -lt 50 ]]; then SIZE="moderate"; else SIZE="major"; fi; MSG="Update $FILENAME: $SIZE changes ($CHANGED_LINES lines)"; git commit -m "$MSG" "$CLAUDE_TOOL_FILE_PATH" 2>/dev/null || true; fi; fi'';
            }
          ];
        }
        {
          matcher = "Write";
          hooks = [
            {
              type = "command";
              command = ''if git rev-parse --git-dir >/dev/null 2>&1 && [[ -n "$CLAUDE_TOOL_FILE_PATH" ]]; then git add "$CLAUDE_TOOL_FILE_PATH" 2>/dev/null; FILENAME=$(basename "$CLAUDE_TOOL_FILE_PATH"); git commit -m "Add new file: $FILENAME" "$CLAUDE_TOOL_FILE_PATH" 2>/dev/null || true; fi'';
            }
          ];
        }
      ];
    };
    statusLine = {
      type = "command";
      command = "~/.claude/statusline.sh";
    };
    enabledPlugins."claude-security@claude-plugins-official" = true;
    extraKnownMarketplaces.claude-plugins-official.source = {
      source = "github";
      repo = "anthropics/claude-plugins-official";
    };
    alwaysThinkingEnabled = true;
  };

  opencodeConfig = {
    "$schema" = "https://opencode.ai/config.json";
    model = "opencode-go/glm-5.2";
    plugin = ["@franlol/opencode-md-table-formatter@0.0.3"];
    autoupdate = false;
  };
  opencodeTui = {
    "$schema" = "https://opencode.ai/tui.json";
    theme = "opencode";
    plugin = [];
  };
  json = pkgs.formats.json {};
in {
  home.packages =
    [
      claude-code
      opencode
      oh-my-opencode
      pkgs.bun # opencode's plugin system
      pkgs.ast-grep # oh-my-opencode
      pkgs.jq # statusline.sh
    ]
    ++ skills.packages pkgs;

  home.file =
    {
      ".claude/settings.json".source = json.generate "claude-settings.json" claudeSettings;
      ".claude/statusline.sh" = {
        source = ./agents/statusline.sh;
        executable = true;
      };
      ".claude/RTK.md".source = rtkMd;
      ".omo/omo.jsonc".source =
        config.lib.file.mkOutOfStoreSymlink "/srv/the-hive/dotfiles/opencode/omo.jsonc";
    }
    // skills.mkSkillFiles ".claude/skills";

  xdg.configFile =
    {
      "opencode/opencode.json".source = json.generate "opencode.json" opencodeConfig;
      "opencode/tui.json".source = json.generate "tui.json" opencodeTui;
      # `omo doctor` will still say "not registered" -- it only knows the npm
      # route; ignore that line.
      "opencode/plugins/oh-my-openagent.ts".source = omoShim;

      # post-dellvis-tooling §3. Telemetry is already off via
      # RTK_TELEMETRY_DISABLED (agent-proxy.nix); nix stays with nixq.
      "rtk/config.toml".source = (pkgs.formats.toml {}).generate "rtk-config.toml" {
        hooks.exclude_commands = ["nix" "nixos-rebuild" "colmena" "nom" "just"];
        tee = {
          enabled = true;
          mode = "failures";
        };
        telemetry.enabled = false;
      };
    }
    // skills.mkSkillFiles "opencode/skills";
}
